"""
Integration with smol-dev for code generation.
"""

import os
import click
from typing import Dict, List, Optional, Union
import tempfile

try:
    from smol_dev.generate import generate_code
except ImportError:
    # Fallback function if smol-dev is not installed
    async def generate_code(prompt: str, system_prompt: str = None, out_path: str = None):
        """Fallback function when smol-dev is not available."""
        click.secho("Error: smol-dev package is not installed. Please install it with 'pip install smol-dev'.", fg="red")
        return None


async def generate_files_from_prompt(
    prompt: str, 
    output_directory: str, 
    system_prompt: Optional[str] = None,
    verbose: bool = True
) -> Dict[str, str]:
    """
    Uses smol-dev to generate files from a prompt.
    
    Args:
        prompt: The prompt to generate files from
        output_directory: Directory where files should be saved
        system_prompt: Optional system prompt to guide generation
        verbose: Whether to show verbose output
        
    Returns:
        Dictionary mapping filenames to their content
    """
    if verbose:
        click.secho(f"Generating files using smol-dev in {output_directory}...", fg="blue")
    
    # Create a temporary directory for smol-dev output
    with tempfile.TemporaryDirectory() as temp_dir:
        # Call smol-dev to generate the files
        result = await generate_code(
            prompt=prompt,
            system_prompt=system_prompt,
            out_path=temp_dir
        )
        
        if not result:
            click.secho("File generation failed. Please check if smol-dev is installed correctly.", fg="red")
            return {}
        
        # Read the generated files
        generated_files = {}
        for root, _, files in os.walk(temp_dir):
            for file in files:
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, temp_dir)
                
                # Skip internal files that might be generated by smol-dev
                if rel_path.startswith('.') or rel_path == 'shared_dependencies.md':
                    continue
                
                try:
                    with open(file_path, 'r') as f:
                        content = f.read()
                    
                    generated_files[rel_path] = content
                    
                    # Save to the output directory as well
                    out_file_path = os.path.join(output_directory, rel_path)
                    os.makedirs(os.path.dirname(out_file_path), exist_ok=True)
                    
                    with open(out_file_path, 'w') as f:
                        f.write(content)
                    
                    if verbose:
                        click.secho(f"Generated: {rel_path}", fg="green")
                        
                except Exception as e:
                    if verbose:
                        click.secho(f"Error processing {rel_path}: {str(e)}", fg="red")
    
    return generated_files


async def generate_single_file(
    prompt: str,
    filename: str,
    output_directory: str,
    system_prompt: Optional[str] = None,
    verbose: bool = True
) -> Optional[str]:
    """
    Uses smol-dev to generate a single file from a prompt.
    
    Args:
        prompt: The prompt to generate the file from
        filename: The name of the file to generate
        output_directory: Directory where the file should be saved
        system_prompt: Optional system prompt to guide generation
        verbose: Whether to show verbose output
        
    Returns:
        The content of the generated file, or None if generation failed
    """
    # Create a more specific prompt focused on single file generation
    focused_prompt = f"""
Generate a single file named {filename}.

{prompt}

Output only the content of the {filename} file, without any markdown code block formatting.
"""
    
    if verbose:
        click.secho(f"Generating {filename} using smol-dev in {output_directory}...", fg="blue")
    
    # Create a temporary directory for smol-dev output
    with tempfile.TemporaryDirectory() as temp_dir:
        # Call smol-dev to generate the file
        result = await generate_code(
            prompt=focused_prompt,
            system_prompt=system_prompt,
            out_path=temp_dir
        )
        
        if not result:
            click.secho(f"File generation failed for {filename}. Please check if smol-dev is installed correctly.", fg="red")
            return None
        
        # Find the generated file or use the first file generated
        temp_file_path = None
        for root, _, files in os.walk(temp_dir):
            for file in files:
                if file == filename or not temp_file_path:
                    temp_file_path = os.path.join(root, file)
                    if file == filename:
                        break
        
        if not temp_file_path:
            click.secho(f"No files were generated for {filename}.", fg="red")
            return None
        
        try:
            with open(temp_file_path, 'r') as f:
                content = f.read()
            
            # Save to the output directory
            os.makedirs(output_directory, exist_ok=True)
            out_file_path = os.path.join(output_directory, filename)
            
            with open(out_file_path, 'w') as f:
                f.write(content)
            
            if verbose:
                click.secho(f"Generated: {filename}", fg="green")
            
            return content
                    
        except Exception as e:
            if verbose:
                click.secho(f"Error processing {filename}: {str(e)}", fg="red")
            return None 